steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Docker Version
  args: ["version"]
- name: 'alpine'
  id:  Rocker Verse Test
  args: ["echo", "Rocker Verse Test"]
- name: 'rocker/verse'
  id: Hello R
  args: ["R", "-e", "paste0('1 + 1 = ', 1+1)"]
